# _*_ coding: utf-8

from Letters import *

# -------------------------------------
# set of dictionaries for Orthodox fonts
# this is short form - symbols are not matching with Ponomar Unicode
# (matching symbols not replaced).

font_table_triodion = {
    '#': Zvatelce,
    '$': Zvatelce + Oxia,
    '%': Zvatelce + Varia,
    '&': Titlo,
    '+': '\u2DE1' + Pokrytie,
    '0': unicSmallO + Oxia,
    '1': Oxia,
    '2': Varia,
    '3': Zvatelce,
    '4': Zvatelce + Oxia,
    '5': Zvatelce + Varia,
    '6': Kamora,
    '7': Titlo,
    '8': '\u033E',
    '9': '\u0436' + Titlo,
    '<': '\u2DEF',
    '=': '\u2DE9' + Pokrytie,
    '>': '\u2DEC' + Pokrytie,
    '?': '\u2DF1' + Pokrytie,
    '@': Varia,
    'A': '\u0430' + Varia,
    'B': unicSmallYat + Kamora,
    'C': '\u2DED' + Pokrytie,
    'D': '\u0434' + '\u2DED' + Pokrytie,
    'E': unicSmallIe + Varia,
    'F': unicCapitalFita,
    'G': '\u0433' + Titlo,
    'H': unicSmallOmega + Oxia,
    'I': unicCapitalUkrI,
    'J': unicSmallUkrI + Varia,
    'K': '\uA656' + Zvatelce,
    'L': '\u043B' + '\u2DE3',
    'M': unicCapitalIzhitsaDblGrave,
    'N': unicCapitalRoundOmega + Zvatelce,
    'O': unicCapitalRoundOmega,
    'P': '\u0470',
    'Q': unicCapitalOmegaTitled,
    'R': '\u0440' + Titlo,
    'S': unicSmallLittleYus + Varia,
    'T': '\u047E',
    'U': unicCapitalUk,
    'V': unicCapitalIzhitsa,
    'W': unicCapitalOmega,
    'X': '\u046E',
    'Y': unicSmallMonogrUk + Varia,
    'Z': unicCapitalLittleYus,
    '\\': Titlo,
    '^': Kamora,
    '_': '\u033E',
    'a': '\u0430' + Oxia,
    'b': '\u2DEA' + Pokrytie,
    'c': '\u2DED' + Pokrytie,
    'd': '\u2DE3',
    'e': unicSmallIe + Oxia,
    'f': unicSmallFita,
    'g': '\u2DE2' + Pokrytie,
    'h': '\u044B' + Oxia,
    'i': unicSmallUkrI,
    'j': unicSmallUkrI + Oxia,
    'k': '\uA657' + Zvatelce,
    'l': '\u043B' + Titlo,
    'm': unicSmallIzhitsaDblGrave,
    'n': unicSmallRoundOmega + Zvatelce,
    'o': unicSmallRoundOmega,
    'p': '\u0471',
    'q': unicSmallOmegaTitled,
    'r': '\u0440' + '\u2DED' + Pokrytie,
    's': unicSmallLittleYus + Oxia,
    't': '\u047F',
    'u': unicSmallUk,
    'v': unicSmallIzhitsa,
    'w': unicSmallOmega,
    'x': '\u046F',
    'y': unicSmallMonogrUk + Oxia,
    'z': unicSmallLittleYus,
    '{': unicSmallMonogrUk + Kamora,
    '|': unicSmallLittleYus + Zvatelce + Varia,
    '}': unicSmallI + Titlo,
    '~': Oxia,
    '¤': '\u0482',
    '¦': '\u0445' + Titlo,
    '§': '\u0447' + Titlo,
    '©': '\u0441' + Titlo,
    '®': '\u0440' + '\u2DE3',
    '°': '\uA67E',
    '±': '\uA657' + Zvatelce + Varia,
    'µ': unicSmallU,
    'Ё': unicSmallYat + Varia,
    'Ђ': unicSmallIzhitsa + Oxia,
    'Ѓ': '\u0410' + Zvatelce + Oxia,
    'І': unicCapitalYi,
    'Ї': unicCapitalUkrI + Zvatelce,
    'Ј': unicCapitalUkrI + Zvatelce + Oxia,
    'Љ': unicCapitalLittleYus + Zvatelce,
    'Њ': unicCapitalOmega + Zvatelce,
    'Ћ': '\uA656' + Zvatelce + Oxia,
    'Ќ': unicCapitalUk + Zvatelce + Oxia,
    'Ў': unicCapitalUk + Zvatelce,
    'Џ': unicCapitalRoundOmega + Zvatelce + Oxia,
    'Э': unicCapitalYat,
    'Я': '\uA656',
    'э': unicSmallYat,
    'я': '\uA657',
    'ё': unicSmallYat + Oxia,
    'ђ': unicSmallIzhitsa + '\u2DE2' + Pokrytie,
    'ѓ': '\u0430' + Zvatelce + Oxia,
    'і': unicSmallUkrI + Kendema,
    'ї': unicSmallUkrI + Zvatelce,
    'ј': unicSmallUkrI + Zvatelce + Oxia,
    'љ': unicSmallLittleYus + Zvatelce,
    'њ': unicSmallOmega + Zvatelce,
    'ћ': '\uA657' + Zvatelce + Oxia,
    'ќ': unicSmallUk + Zvatelce + Oxia,
    'ў': unicSmallUk + Zvatelce,
    'џ': unicSmallRoundOmega + Zvatelce + Oxia,
    'Ґ': '\u0410' + Zvatelce,
    'ґ': '\u0430' + Zvatelce,
    '†': '\u0430' + Kamora,
    '‡': unicSmallUkrI + Kamora,
    '•': '\u2DE4',
    '…': '\u046F' + Titlo,
    '‰': unicSmallLittleYus + Kamora,
    '‹': unicSmallUkrI + Titlo,
    '›': unicSmallIzhitsa + Kamora,
    '€': '\u2DE5',
    '№': '\u0430' + Titlo,
    '™': '\u0442' + Titlo,
    'У': unicCapitalMonogrUk,
    'у': unicSmallMonogrUk,
}

font_table_orthodox_tt = {
    '#': Zvatelce,
    '$': Zvatelce + Oxia,
    '%': Zvatelce + Varia,
    '&': Titlo,
    '+': '\u2DE1' + Pokrytie,
    '0': unicSmallO + Oxia,
    '1': Oxia,
    '2': Varia,
    '3': Zvatelce,
    '4': Zvatelce + Oxia,
    '5': Zvatelce + Varia,
    '6': Kamora,
    '7': Titlo,
    '8': '\u033E',
    '9': '\u0436' + Titlo,
    '<': '\u2DEF',
    '=': '\u2DE9' + Pokrytie,
    '>': '\u2DEC' + Pokrytie,
    '?': '\u2DF1' + Pokrytie,
    '@': Varia,
    'A': '\u0430' + Varia,
    'B': unicSmallYat + Kamora,
    'C': '\u2DED' + Pokrytie,
    'D': '\u0434' + '\u2DED' + Pokrytie,
    'E': unicSmallIe + Varia,
    'F': unicCapitalFita,
    'G': '\u0433' + Titlo,
    'H': unicSmallOmega + Oxia,
    'I': unicCapitalUkrI,
    'J': unicSmallUkrI + Varia,
    'K': '\uA656' + Zvatelce,
    'L': '\u043B' + '\u2DE3',
    'M': unicCapitalIzhitsaDblGrave,
    'N': unicCapitalRoundOmega + Zvatelce,
    'O': unicCapitalRoundOmega,
    'P': '\u0470',
    'Q': unicCapitalOmegaTitled,
    'R': '\u0440' + Titlo,
    'S': unicSmallLittleYus + Varia,
    'T': '\u047E',
    'U': unicCapitalUk,
    'V': unicCapitalIzhitsa,
    'W': unicCapitalOmega,
    'X': '\u046E',
    'Y': unicSmallMonogrUk + Varia,
    'Z': unicCapitalLittleYus,
    '\\': Titlo,
    '^': Kamora,
    '_': '\u033E',
    'a': '\u0430' + Oxia,
    'b': '\u2DEA' + Pokrytie,
    'c': '\u2DED' + Pokrytie,
    'd': '\u2DE3',
    'e': unicSmallIe + Oxia,
    'f': unicSmallFita,
    'g': '\u2DE2' + Pokrytie,
    'h': '\u044B' + Oxia,
    'i': unicSmallUkrI,
    'j': unicSmallUkrI + Oxia,
    'k': '\uA657' + Zvatelce,
    'l': '\u043B' + Titlo,
    'm': unicSmallIzhitsaDblGrave,
    'n': unicSmallRoundOmega + Zvatelce,
    'o': unicSmallRoundOmega,
    'p': '\u0471',
    'q': unicSmallOmegaTitled,
    'r': '\u0440' + '\u2DED' + Pokrytie,
    's': unicSmallLittleYus + Oxia,
    't': '\u047F',
    'u': unicSmallUk,
    'v': unicSmallIzhitsa,
    'w': unicSmallOmega,
    'x': '\u046F',
    'y': unicSmallMonogrUk + Oxia,
    'z': unicSmallLittleYus,
    '{': unicSmallMonogrUk + Kamora,
    '|': unicSmallLittleYus + Zvatelce + Varia,
    '}': unicSmallI + Titlo,
    '~': Oxia,
    '¤': '\u0482',
    '¦': '\u0445' + Titlo,
    '§': '\u0447' + Titlo,
    '©': '\u0441' + Titlo,
    '®': '\u0440' + '\u2DE3',
    '°': '\uA67E',
    '±': '\uA657' + Zvatelce + Varia,
    'µ': unicSmallU,
    'Ё': unicSmallYat + Varia,
    'Ђ': unicSmallIzhitsa + Oxia,
    'Ѓ': '\u0410' + Zvatelce + Oxia,
    'І': unicCapitalUkrI,
    'Ї': unicCapitalUkrI + Zvatelce,
    'Ј': unicCapitalUkrI + Zvatelce + Oxia,
    'Љ': unicCapitalLittleYus + Zvatelce,
    'Њ': unicCapitalOmega + Zvatelce,
    'Ћ': '\uA656' + Zvatelce + Oxia,
    'Ќ': unicCapitalUk + Zvatelce + Oxia,
    'Ў': unicCapitalUk + Zvatelce,
    'Џ': unicCapitalRoundOmega + Zvatelce + Oxia,
    'Э': unicCapitalYat,
    'Я': '\uA656',
    'э': unicSmallYat,
    'я': '\uA657',
    'ё': unicSmallYat + Oxia,
    'ђ': unicSmallIzhitsa + '\u2DE2' + Pokrytie,
    'ѓ': '\u0430' + Zvatelce + Oxia,
    'і': unicSmallUkrI + Kendema,
    'ї': unicSmallUkrI + Zvatelce,
    'ј': unicSmallUkrI + Zvatelce + Oxia,
    'љ': unicSmallLittleYus + Zvatelce,
    'њ': unicSmallOmega + Zvatelce,
    'ћ': '\uA657' + Zvatelce + Oxia,
    'ќ': unicSmallUk + Zvatelce + Oxia,
    'ў': unicSmallUk + Zvatelce,
    'џ': unicSmallRoundOmega + Zvatelce + Oxia,
    'Ґ': '\u0410' + Zvatelce,
    'ґ': '\u0430' + Zvatelce,
    '†': '\u0430' + Kamora,
    '‡': unicSmallUkrI + Kamora,
    '•': '\u2DE4',
    '…': '\u046F' + Titlo,
    '‰': unicSmallLittleYus + Kamora,
    '‹': unicSmallUkrI + Titlo,
    '›': unicSmallIzhitsa + Kamora,
    '€': '\u2DE5',
    '№': '\u0430' + Titlo,
    '™': '\u0442' + Titlo,
    'У': unicCapitalMonogrUk,
    'у': unicSmallMonogrUk,
}

font_table_orthodox_tt_caps = {
    '#': Zvatelce,
    '$': Zvatelce + Oxia,
    '%': Zvatelce + Varia,
    '&': Titlo,
    '+': '\u2DE1' + Pokrytie,
    '0': unicCapitalO + Oxia,
    '1': Oxia,
    '2': Varia,
    '3': Zvatelce,
    '4': Zvatelce + Oxia,
    '5': Zvatelce + Varia,
    '6': Kamora,
    '7': Titlo,
    '8': '\u033E',
    '9': '\u0416' + Titlo,
    '<': '\u2DEF',
    '=': '\u2DE9' + Pokrytie,
    '>': '\u2DEC' + Pokrytie,
    '?': '\u2DF1' + Pokrytie,
    '@': Varia,
    'A': '\u0410' + Varia,
    'B': unicCapitalYat + Kamora,
    'C': '\u2DED' + Pokrytie,
    'D': '\u0414' + '\u2DED' + Pokrytie,
    'E': unicCapitalIe + Varia,
    'F': unicCapitalFita,
    'G': '\u0413' + Titlo,
    'H': unicCapitalOmega + Oxia,
    'I': unicCapitalUkrI,
    'J': unicCapitalUkrI + Varia,
    'K': '\uA656' + Zvatelce,
    'L': '\u041B' + '\u2DE3',
    'M': unicCapitalIzhitsaDblGrave,
    'N': unicCapitalRoundOmega + Zvatelce,
    'O': unicCapitalRoundOmega,
    'P': '\u0470',
    'Q': unicCapitalOmegaTitled,
    'R': '\u0420' + Titlo,
    'S': unicCapitalLittleYus + Varia,
    'T': '\u047E',
    'U': unicCapitalO + unicCapitalMonogrUk,
    'V': unicCapitalIzhitsa,
    'W': unicCapitalOmega,
    'X': '\u046E',
    'Y': unicCapitalMonogrUk + Varia,
    'Z': unicCapitalLittleYus,
    '\\': Titlo,
    '^': Kamora,
    '_': '\u033E',
    'a': '\u0410' + Oxia,
    'b': '\u2DEA' + Pokrytie,
    'c': '\u2DED' + Pokrytie,
    'd': '\u2DE3',
    'e': unicCapitalIe + Oxia,
    'f': unicCapitalFita,
    'g': '\u2DE2' + Pokrytie,
    'h': '\u042B' + Oxia,
    'i': unicCapitalUkrI,
    'j': unicCapitalUkrI + Oxia,
    'k': '\uA656' + Zvatelce,
    'l': '\u041B' + Titlo,
    'm': unicCapitalIzhitsaDblGrave,
    'n': unicCapitalRoundOmega + Zvatelce,
    'o': unicCapitalRoundOmega,
    'p': '\u0470',
    'q': unicCapitalOmegaTitled,
    'r': '\u0420' + '\u2DED' + Pokrytie,
    's': unicCapitalLittleYus + Oxia,
    't': '\u047E',
    'u': unicCapitalO + unicCapitalMonogrUk,
    'v': unicCapitalIzhitsa,
    'w': unicCapitalOmega,
    'x': '\u046E',
    'y': unicCapitalMonogrUk + Oxia,
    'z': unicCapitalLittleYus,
    '{': unicCapitalMonogrUk + Kamora,
    '|': unicCapitalLittleYus + Zvatelce + Varia,
    '}': unicCapitalI + Titlo,
    '~': Oxia,
    '¤': '\u0482',
    '¦': '\u0425' + Titlo,
    '§': '\u0427' + Titlo,
    '©': '\u0421' + Titlo,
    '®': '\u0420' + '\u2DE3',
    '°': '\uA67E',
    '±': '\uA656' + Zvatelce + Varia,
    'µ': unicCapitalMonogrUk,
    '¶': '\u00B6',
    '·': '\u00B7',
    '»': '\u00BB',
    'Ё': unicCapitalYat + Varia,
    'Ђ': unicCapitalIzhitsa + Oxia,
    'Ѓ': '\u0410' + Zvatelce + Oxia,
    'Є': unicCapitalUkrIe,
    'Ї': unicCapitalUkrI + Zvatelce,
    'Ј': unicCapitalUkrI + Zvatelce + Oxia,
    'Љ': unicCapitalLittleYus + Zvatelce,
    'Њ': unicCapitalOmega + Zvatelce,
    'Ћ': '\uA656' + Zvatelce + Oxia,
    'Ќ': unicCapitalO + unicCapitalMonogrUk + Zvatelce + Oxia,
    'Ў': unicCapitalO + unicCapitalMonogrUk + Zvatelce,
    'Џ': unicCapitalRoundOmega + Zvatelce + Oxia,
    'У': unicCapitalMonogrUk,
    'Я': '\uA656',
    'а': '\u0410',
    'б': '\u0411',
    'в': '\u0412',
    'г': '\u0413',
    'д': '\u0414',
    'е': unicCapitalIe,
    'ж': '\u0416',
    'з': '\u0417',
    'и': unicCapitalI,
    'й': '\u0419',
    'к': '\u041A',
    'л': '\u041B',
    'м': '\u041C',
    'н': '\u041D',
    'о': unicCapitalO,
    'п': '\u041F',
    'р': '\u0420',
    'с': '\u0421',
    'т': '\u0422',
    'у': unicCapitalMonogrUk,
    'ф': unicCapitalEf,
    'х': '\u0425',
    'ц': '\u0426',
    'ч': '\u0427',
    'ш': '\u0428',
    'щ': '\u0429',
    'ъ': '\u042A',
    'ы': '\u042B',
    'ь': '\u042C',
    'э': unicCapitalYat,
    'ю': '\u042E',
    'я': '\uA656',
    'ё': unicCapitalYat + Oxia,
    'ђ': unicCapitalIzhitsa + '\u2DE2' + Pokrytie,
    'ѓ': '\u0410' + Zvatelce + Oxia,
    'є': unicCapitalUkrIe,
    'ѕ': '\u0405',
    'і': unicCapitalUkrI,
    'ї': unicCapitalUkrI + Zvatelce,
    'ј': unicCapitalUkrI + Zvatelce + Oxia,
    'љ': unicCapitalLittleYus + Zvatelce,
    'њ': unicCapitalOmega + Zvatelce,
    'ћ': '\uA656' + Zvatelce + Oxia,
    'ќ': unicCapitalO + unicCapitalMonogrUk + Zvatelce + Oxia,
    'ў': unicCapitalO + unicCapitalMonogrUk + Zvatelce,
    'џ': unicCapitalRoundOmega + Zvatelce + Oxia,
    'Ґ': '\u0410' + Zvatelce,
    'ґ': '\u0410' + Zvatelce,
    '†': '\u0410' + Kamora,
    '‡': unicCapitalUkrI + Kamora,
    '•': '\u2DE4',
    '…': '\u046E' + Titlo,
    '‰': unicCapitalLittleYus + Kamora,
    '‹': unicCapitalUkrI + Titlo,
    '›': unicCapitalIzhitsa + Kamora,
    '€': '\u2DE5',
    '№': '\u0410' + Titlo,
    "™": '\u0422' + Titlo,
}

font_table_orthodox_e_roos = {
    '#': '\uD83D' + '\uDD44',
    '$': '\uD83D' + '\uDD42',
    '%': '\uD83D' + '\uDD41',
    '0': unicDigitZero,
    '1': unicDigitOne,
    '2': unicDigitTwo,
    '3': unicDigitThree,
    '4': unicDigitFour,
    '5': unicDigitFive,
    '6': unicDigitSix,
    '7': unicDigitSeven,
    '8': unicDigitEight,
    '9': unicDigitNine,
    '@': '\uD83D' + '\uDD43',
    'A': '\u0410' + Oxia,
    'E': unicCapitalIe + Oxia,
    'I': unicCapitalUkrI,
    'M': '\uD83D' + '\uDD45',
    'O': unicCapitalRoundOmega,
    'U': unicCapitalMonogrUk + Oxia,
    'V': unicCapitalIzhitsa + Oxia,
    'W': unicCapitalO + Oxia,
    'Y': '\u042B' + Oxia,
    '^': '\uD83D' + '\uDD40',
    'a': '\u0430' + Oxia,
    'e': unicSmallIe + Oxia,
    'i': unicSmallUkrI,
    'o': unicSmallRoundOmega,
    'u': unicSmallU + Oxia,
    'v': unicSmallIzhitsa + Oxia,
    'w': unicSmallO + Oxia,
    'y': '\u044B' + Oxia,
    'Ђ': unicCapitalYat + Oxia,
    'Є': '\uE1A5',
    'Ј': unicCapitalUkrI + Oxia,
    'Њ': Oxia,
    'Ћ': unicCapitalYat,
    'Ќ': unicCapitalFita,
    'Џ': unicCapitalIzhitsa,
    'ђ': unicSmallYat + Oxia,
    'і': unicSmallUkrIWithDot,
    'ј': unicSmallUkrI + Oxia,
    'њ': Oxia,
    'ћ': unicSmallYat,
    'ќ': unicSmallFita,
    'џ': unicSmallIzhitsa,
    '†': CrossOrthodox,
    '‡': Dagger,
    'У': unicCapitalMonogrUk,
    "Ў": unicCapitalMonogrUk + '\u0306',
}

font_table_orthodox_digits_loose = {
    '!': '\uD83D' + '\uDD43',
    '#': '\uD83D' + '\uDD42',
    '$': '\uD83D' + '\uDD41',
    '%': '\uD83D' + '\uDD40',
    '+': Dagger,
    ',': '\u002C',
    '.': '\u002E',
    '0': '\u0482',
    '1': '\u0430' + '\u20DD',
    '2': '\u0430' + '\u0488',
    '3': '\u0430' + '\u0489',
    '4': '\u0430' + '\uA670',
    '5': '\u0430' + '\uA671',
    '6': '\u044B' + '\uA672',
    ';': '\u002E',
    '=': CrossOrthodox,
    '?': '\u003B',
    '@': '\uD83D' + '\uDD43',
    'E': unicSmallUkrIe + Titlo,
    'F': unicSmallFita + Titlo,
    'J': unicSmallUkrI + Titlo,
    'K': '\u046F' + Titlo,
    'M': '\uD83D' + '\uDD45',
    'O': unicSmallRoundOmega + Titlo,
    'P': '\u0471' + Titlo,
    'S': '\u0455' + Titlo,
    'T': '\u047F',
    'W': unicSmallOmega + Titlo,
    'e': unicSmallUkrIe,
    'f': unicSmallFita,
    'j': unicSmallUkrI,
    'k': '\u046F',
    'o': unicSmallRoundOmega,
    'p': '\u0471',
    's': '\u0455',
    't': '\u047F',
    'w': unicSmallOmega,
    ';': '\u002E',
    'А': '\u0430' + Titlo,
    'Б': '\u0431' + Titlo,
    'В': '\u0432' + Titlo,
    'Г': '\u0433' + Titlo,
    'Д': '\u0434' + Titlo,
    'Е': unicSmallIe + Titlo,
    'Ж': '\u0436' + Titlo,
    'З': '\u0437' + Titlo,
    'И': unicSmallI + Titlo,
    'К': '\u043A' + Titlo,
    'Л': '\u043B' + Titlo,
    'М': '\u043C' + Titlo,
    'Н': '\u043D' + Titlo,
    'О': unicSmallO + Titlo,
    'П': '\u043F' + Titlo,
    'Р': '\u0440' + Titlo,
    'С': '\u0441' + Titlo,
    'Т': '\u0442' + Titlo,
    'У': unicSmallU + Titlo,
    'Ф': unicSmallEf + Titlo,
    'Х': '\u0445' + Titlo,
    'Ц': '\u0446' + Titlo,
    'Ч': '\u0447' + Titlo,
    'Ш': '\u0448' + Titlo,
    'Щ': '\u0449' + Titlo,
    'ё': unicSmallYat,
    '∙': '\u00B7',
}

font_table_orthodox_loose = {
    '!': Oxia,
    '"': Varia,
    '#': Zvatelce,
    '$': Zvatelce + Oxia,
    '%': Zvatelce + Oxia,
    '&': Kamora,
    "'": '\uA67E',
    '*': unicSmallUkrI + Zvatelce,
    '+': Titlo,
    '-': '\u005F',
    '0': '\u030F',
    '1': Oxia,
    '2': Varia,
    '3': Zvatelce,
    '4': Zvatelce + Oxia,
    '5': Zvatelce + Varia,
    '6': Kamora,
    '8': unicSmallMonogrUk + Oxia,
    '9': unicSmallMonogrUk + Varia,
    '<': unicCapitalYa,
    '=': Titlo,
    '>': unicSmallYA,
    '?': '\u0021',
    '@': Varia,
    'F': unicCapitalFita,
    'G': '\u2DE4',
    'H': '\u2DEF',
    'I': unicCapitalUkrI,
    'J': unicSmallUkrI + Kamora,
    'K': '\u046E',
    'L': unicSmallYat + Varia,
    'O': unicSmallOmegaTitled,
    'P': '\u0470',
    'Q': unicCapitalO,
    'R': '\u2DEC' + Pokrytie,
    'S': '\u0405',
    'T': '\u047E',
    'U': '\uE3BE',
    'V': unicCapitalIzhitsa,
    'W': unicCapitalOmega,
    'Y': unicSmallU,
    'Z': '\u0302',
    '\\': unicSmallUkrI + Zvatelce + Oxia,
    '^': Zvatelce + Varia,
    '`': '\u2E2F',
    'b': '\u0304',
    'c': '\u2DED' + Pokrytie,
    'd': '\u2DE3',
    'e': unicSmallUkrIe,
    'f': unicSmallFita,
    'g': '\u2DE2' + Pokrytie,
    'h': '\u2DF1' + Pokrytie,
    'i': '\u0457',
    'j': unicSmallUkrI,
    'k': '\u046F',
    'l': unicSmallYat + Kamora,
    'o': unicCapitalRoundOmega,
    'p': '\u0471',
    'q': '\u2DEA' + Pokrytie,
    'r': '\u0440' + Titlo,
    's': '\u0455',
    't': '\u047F',
    'u': unicCapitalUk,
    'v': unicSmallIzhitsa,
    'w': unicSmallOmega,
    'y': unicSmallMonogrUk + Kamora,
    '{': '\u2DE1' + Pokrytie,
    '|': unicCapitalUkrI + Zvatelce + Oxia,
    '}': '\u2DE5',
    '~': '\u2E2F',
    '«': unicSmallUkrI + Oxia,
    'Ё': unicCapitalYat,
    'Ђ': '\u0433' + Titlo,
    'Ѓ': '\u043B' + Titlo,
    'Љ': unicCapitalUk + Zvatelce + Oxia,
    'Њ': unicCapitalUk + Zvatelce + Varia,
    'Ћ': unicSmallRoundOmega + Zvatelce,
    'Ќ': unicSmallUk + Zvatelce + Varia,
    'Џ': unicSmallRoundOmega + Zvatelce + Oxia,
    'О': unicCapitalRoundOmega,
    'У': unicSmallUk,
    'Э': '\uA656',
    'Я': unicCapitalYa,  # unicCapitalLittleYus,
    'у': unicSmallMonogrUk,
    'э': '\uA657',
    'я': unicSmallLittleYus,
    'ё': unicSmallYat,
    'ђ': '\u0430' + Zvatelce + Oxia,
    'ѓ': '\u0445' + Titlo,
    'љ': '\u0436' + Titlo,
    'њ': unicSmallI + Titlo,
    '‘': unicCapitalRoundOmega + Zvatelce,
    '’': unicCapitalRoundOmega + Zvatelce + Oxia,
    '‚': '\u0442' + Titlo,
    '„': '\u0447' + Titlo,
    '†': unicSmallIzhitsa + Zvatelce,
    '‡': unicSmallIzhitsa + Zvatelce + Oxia,
    '…': unicSmallIzhitsa + Oxia,
    '‰': unicSmallUk + Zvatelce,
    '‹': unicSmallUk + Zvatelce + Oxia,
    '€': unicCapitalUk + Zvatelce,
    '№': Zvatelce,
    '™': unicSmallUkrI + Oxia,
}

font_table_ustav = {
    '"': Oxia,
    '#': Zvatelce + Oxia,
    '$': '\u003B',
    '%': Zvatelce,
    '&': Zvatelce + Varia,
    "'": Oxia,
    '*': Zvatelce + Varia,
    '+': '\u033E',
    '/': Titlo,
    '0': unicDigitZero,
    '1': unicDigitOne,
    '2': unicDigitTwo,
    '3': unicDigitThree,
    '4': unicDigitFour,
    '5': unicDigitFive,
    '6': unicDigitSix,
    '7': unicDigitSeven,
    '8': unicDigitEight,
    '9': unicDigitNine,
    ':': '\u003A',
    ';': '\u003B',
    '<': '\u00AB',
    '=': '\u033E',
    '>': '\u00BB',
    '@': Zvatelce + Oxia,
    'A': '\uA656',
    'B': unicCapitalUkrI,
    'C': '\u2DED' + Pokrytie,
    'D': '\u2DE3',
    'E': unicCapitalYat,
    'F': unicCapitalFita,
    'G': '\u2DE2' + Pokrytie,
    'H': unicCapitalIzhitsaDblGrave,
    'I': unicCapitalYi,
    'J': unicCapitalRoundOmega,
    'K': '\u046E',
    'L': '\uA67E',
    'M': Oxia,
    'N': '\u047E',
    'O': '\u2DEA' + Pokrytie,
    'P': '\u0470',
    'Q': unicCapitalOmegaTitled,
    'R': Pokrytie,
    'S': '\u0405',
    'T': '\u0465',
    'U': unicSmallMonogrUk,
    'V': unicCapitalIzhitsa,
    'W': unicCapitalOmega,
    'X': '\u2DF1' + Pokrytie,
    'Y': unicCapitalUk,
    'Z': unicCapitalYa,
    '\\': Titlo,
    '^': Zvatelce,
    '`': Varia,
    'a': '\uA657',
    'b': unicSmallUkrI,
    'c': '\u2DED' + Pokrytie,
    'd': '\u2DE3',
    'e': unicSmallYat,
    'f': unicSmallFita,
    'g': '\u2DE2' + Pokrytie,
    'h': unicSmallIzhitsaDblGrave,
    'i': unicSmallUkrI + Kendema,
    'j': unicSmallRoundOmega,
    'k': '\u046F',
    'l': '\u1C82',
    'm': Oxia,
    'n': '\u047F',
    'o': '\u2DEA' + Pokrytie,
    'p': '\u0471',
    'q': unicSmallOmegaTitled,
    'r': Pokrytie,
    's': '\u0455',
    't': unicSmallUkrIe,
    'u': unicSmallMonogrUk,
    'v': unicSmallIzhitsa,
    'w': unicSmallOmega,
    'x': Varia,
    'y': unicSmallUk,
    'z': unicSmallYA,
    '{': Kamora,
    '|': Titlo,
    '}': Kamora,
    '~': Varia,
    '': unicCapitalIotifLittleYus,
    '': unicCapitalYa,
    '': '\u046B',
    '': '\u2DF1' + Pokrytie,
    '': unicCapitalFita,
    '': unicSmallIotifLittleYus,
    '': '\u040B',
    '': '\u1C82',
    '¡': unicCapitalUk,
    '¢': unicSmallUk,
    '£': unicCapitalIzhitsaDblGrave,
    '¥': '\u047E',
    '¨': Varia,
    'ª': '\uA67E',
    '¯': unicCapitalYi,
    '²': unicCapitalUkrI,
    '³': unicSmallUkrI,
    '´': '\u047F',
    'µ': unicSmallMonogrUk + Varia,
    '¸': '\uA657',
    '¹': '\u0482',
    'º': unicSmallUkrIe,
    '¼': unicSmallIzhitsaDblGrave,
    '½': '\u0405',
    '¾': '\u0455',
    '¿': '\u0457',
    'À': '\u0410',
    'Á': '\u0411',
    'Â': '\u0412',
    'Ã': '\u0413',
    'Ä': '\u0414',
    'Å': unicCapitalIe,
    'Æ': '\u0416',
    'Ç': '\u0417',
    'È': unicCapitalI,
    'É': '\u0419',
    'Ê': '\u041A',
    'Ë': '\u041B',
    'Ì': '\u041C',
    'Í': '\u041D',
    'Î': unicCapitalO,
    'Ï': '\u041F',
    'Ð': '\u0420',
    'Ñ': '\u0421',
    'Ò': '\u0422',
    'Ó': unicCapitalMonogrUk,
    'Ô': unicCapitalEf,
    'Õ': '\u0425',
    'Ö': '\u0426',
    '×': '\u0427',
    'Ø': '\u0428',
    'Ù': '\u0429',
    'Ú': '\u042A',
    'Û': '\u042B',
    'Ü': '\u042C',
    'Ý': '\u042D',
    'Þ': '\u042E',
    'ß': unicCapitalLittleYus,
    'à': '\u0430',
    'á': '\u0431',
    'â': '\u0432',
    'ã': '\u0433',
    'ä': '\u0434',
    'å': unicSmallIe,
    'æ': '\u0436',
    'ç': '\u0437',
    'è': unicSmallI,
    'é': '\u0439',
    'ê': '\u043A',
    'ë': '\u043B',
    'ì': '\u043C',
    'í': '\u043D',
    'î': unicSmallO,
    'ï': '\u043F',
    'ð': '\u0440',
    'ñ': '\u0441',
    'ò': '\u0442',
    'ó': unicSmallU,
    'ô': unicSmallEf,
    'õ': '\u0445',
    'ö': '\u0446',
    '÷': '\u0447',
    'ø': '\u0448',
    'ù': '\u0449',
    'ú': '\u044A',
    'û': '\u044B',
    'ü': '\u044C',
    'ý': '\u044D',
    'þ': '\u044E',
    'ÿ': unicSmallLittleYus,
    'Œ': unicSmallU,
    'œ': '\u045B',
    'Š': '\u0470',
    'š': '\u046D',
    'Ÿ': unicCapitalUkrI,
    'ƒ': unicCapitalYa,
    '˜': '\u2053',
    'Ё': Varia,
    'Ђ': unicCapitalIotifLittleYus,
    'Ѓ': unicCapitalYa,
    'Є': '\uA67E',
    'Ѕ': '\u0405',
    'Ј': unicCapitalIzhitsaDblGrave,
    'Ћ': '\u2DF1' + Pokrytie,
    'Ќ': '\u046B',
    'Ў': unicCapitalUk,
    'Џ': unicCapitalFita,
    'Я': unicCapitalLittleYus,
    'я': unicSmallLittleYus,
    'ё': '\uA657',
    'ђ': unicSmallIotifLittleYus,
    'ј': unicSmallIzhitsaDblGrave,
    'ћ': '\u1C82',
    'ќ': '\u040B',
    'ў': unicSmallUk,
    'Ґ': '\u047E',
    'ґ': '\u047F',
    '‘': Oxia,
    '’': Oxia,
    '‚': '\u002C',
    '“': Oxia,
    '”': Oxia,
    '‡': CrossOrthodox,
    '№': '\u0482',
    '™': '\u002A',
    'У': unicCapitalMonogrUk,
}

font_table_valaam = {
    '"': '\u030F',
    '#': '\u0482',
    '$': '\u003B',
    '%': Zvatelce,
    '&': Zvatelce,
    "'": Oxia,
    '*': '\u002A',
    '+': '\u033E',
    '/': Oxia,
    '0': unicDigitZero,
    '1': unicDigitOne,
    '2': unicDigitTwo,
    '3': unicDigitThree,
    '4': unicDigitFour,
    '5': unicDigitFive,
    '6': unicDigitSix,
    '7': unicDigitSeven,
    '8': unicDigitEight,
    '9': unicDigitNine,
    '<': '\u00AB',
    '=': '\uA67E',
    '>': '\u00BB',
    '@': Zvatelce + Oxia,
    'A': unicCapitalIotifLittleYus,
    'B': unicCapitalUkrI,
    'C': '\u2DED' + Pokrytie,
    'D': '\u2DE3',
    'E': unicCapitalYat,
    'F': unicCapitalFita,
    'G': '\u2DE2' + Pokrytie,
    'H': '\u040B',
    'I': unicCapitalUkrI,
    'J': unicCapitalRoundOmega + Zvatelce,
    'K': '\u046E',
    'L': Zvatelce + Varia,
    'M': Zvatelce + Varia,
    'N': '\u2DEA' + Pokrytie,
    'O': '\u047E',
    'P': '\u0470',
    'Q': unicCapitalBroadOmega,
    'R': Pokrytie,
    'S': '\u0405',
    'T': '\u0465',
    'U': unicSmallMonogrUk,
    'V': unicCapitalIzhitsa,
    'W': unicCapitalOmega,
    'X': Zvatelce + Oxia,
    'Y': unicCapitalUk,
    'Z': '\uA656',
    '\\': Varia,
    '^': Pokrytie,
    '_': '\u2014',
    '`': Varia,
    'a': unicSmallIotifLittleYus,
    'b': '\u046D',
    'c': '\u2DED' + Pokrytie,
    'd': '\u2DE3',
    'e': unicSmallYat,
    'f': unicSmallFita,
    'g': '\u2DE2' + Pokrytie,
    'h': '\u045B',
    'i': '\u0457',
    'j': unicSmallRoundOmega + Zvatelce,
    'k': '\u046F',
    'l': Zvatelce + Varia,
    'm': Zvatelce + Varia,
    'n': '\u2DEA' + Pokrytie,
    'o': '\u047F',
    'p': '\u0471',
    'q': unicSmallUkrI,
    'r': '\u046B',
    's': '\u0455',
    't': unicSmallIe,
    'u': unicSmallMonogrUk,
    'v': unicSmallIzhitsa,
    'w': unicSmallOmega,
    'x': Zvatelce + Oxia,
    'y': unicSmallUk,
    'z': '\uA657',
    '|': Kamora,
    '~': Titlo,
    '': '\u2DF1' + Pokrytie,
    '¨': Titlo,
    '´': unicCapitalMonogrUk,
    'µ': '\u2DE8',
    '¸': '\u033E',
    '¹': '\u2116',
    'À': '\u0410',
    'Á': '\u0411',
    'Â': '\u0412',
    'Ã': '\u0413',
    'Ä': '\u0414',
    'Å': unicCapitalIe,
    'Æ': '\u0416',
    'Ç': '\u0417',
    'È': unicCapitalI,
    'É': '\u0419',
    'Ê': '\u041A',
    'Ë': '\u041B',
    'Ì': '\u041C',
    'Í': '\u041D',
    'Î': unicCapitalO,
    'Ï': '\u041F',
    'Ð': '\u0420',
    'Ñ': '\u0421',
    'Ò': '\u0422',
    'Ó': unicCapitalMonogrUk,
    'Ô': unicCapitalEf,
    'Õ': '\u0425',
    'Ö': '\u0426',
    '×': '\u0427',
    'Ø': '\u0428',
    'Ù': '\u0429',
    'Ú': '\u042A',
    'Û': '\u042B',
    'Ü': '\u042C',
    'Ý': '\u042D',
    'Þ': '\u042E',
    'ß': unicCapitalLittleYus,
    'à': '\u0430',
    'á': '\u0431',
    'â': '\u0432',
    'ã': '\u0433',
    'ä': '\u0434',
    'å': unicSmallIe,
    'æ': '\u0436',
    'ç': '\u0437',
    'è': unicSmallI,
    'é': '\u0439',
    'ê': '\u043A',
    'ë': '\u043B',
    'ì': '\u043C',
    'í': '\u043D',
    'î': unicSmallO,
    'ï': '\u043F',
    'ð': '\u0440',
    'ñ': '\u0441',
    'ò': '\u0442',
    'ó': unicSmallU,
    'ô': unicSmallEf,
    'õ': '\u0445',
    'ö': '\u0446',
    '÷': '\u0447',
    'ø': '\u0448',
    'ù': '\u0449',
    'ú': '\u044A',
    'û': '\u044B',
    'ü': '\u044C',
    'ý': '\u044D',
    'þ': '\u044E',
    'ÿ': unicSmallLittleYus,
    'Œ': unicSmallUkrIWithDot,
    'Š': '\u2DE9' + Pokrytie,
    'ƒ': '\u0027',
    'ˆ': '\u0485',
    'μ': '\u2DE8',
    'Ё': Titlo,
    'Ѓ': '\u2DF0' + Pokrytie,
    'Ќ': '\u2DED' + Pokrytie,
    'У': unicCapitalMonogrUk,
    'Я': unicCapitalLittleYus,
    'я': unicSmallLittleYus,
    'ё': '\u033E',
    '‐': '\u002D',
    '–': '\u0027',
    '‘': Oxia,
    '’': Oxia,
    '“': '\u030F',
    '”': '\u030F',
    '„': '\u2DE6' + Pokrytie,
    '†': CrossOrthodox,
    '‡': CrossOrthodox,
    '…': '\u2DE7' + Pokrytie,
    '‰': Kendema,
    '‹': '\u2DE4',
    '™': '\u2DEF',
}

font_table_hirmos_ponomar = {
    '0': unicDigitZero,
    '1': unicDigitOne,
    '2': unicDigitTwo,
    '3': unicDigitThree,
    '4': unicDigitFour,
    '5': unicDigitFive,
    '6': unicDigitSix,
    '7': unicDigitSeven,
    '8': unicDigitEight,
    '9': unicDigitNine,
    'Ў': '\uE3BF',
    'У': unicCapitalMonogrUk,
    '': '\uEF00',
    '': '\uEF01',
    '': '\uEF02',
    '': '\uEF03',
    '': '\uEF04',
    '': '\uEF05',
    '': '\uEF06',
    '': '\uEF07',
    '': '\uEF08',
    '': '\uEF09',
    '': '\uEF0A',
    '': '\uEF0B',
    '': '\uEF10',
    '': '\uEF11',
    '': '\uEF12',
    '': '\uEF13',
    '': '\uEF14',
    '': '\uEF15',
    '': '\uEF16',
    '': '\uEF17',
    '': '\uE5D0',
    '': '\uE5D1',
    '': '\uE5D2',
    '': '\uE5D3',
    '': ZvatelceUp,
    '': Iso,
    '': IsoUp,
    '': Apostrof,
    '': ApostrofUp,
    '': ApostrofGreat,
    '': '\uE016',
    '': '\uDB80' + '\uDC23',
    '': '\uDB80' + '\uDC30',
    '': '\uE0E2',
    '': '\uE0E4',
    '': '\uE0EC',
    '': '\uE0ED',
    '': '\uE612',
    '': '\uE714',
    '': '\uE800',
    '': '\uE92D',
    '': '\uE92E',
    '': '\uE8E5',
    '': '\uE901',
    '': '\uE903',
    '': '\uE904',
    '': '\uE928',
    '': unicSmallUkrIWithDot,
}

font_table_irmologion = {
    '#': '\u0482',
    '$': '\uD83D' + '\uDD40',
    '%': NotationDoubleSlash,
    '&': '\uD83D' + '\uDD41',
    "'": Oxia,
    '0': unicDigitZero,
    '1': unicDigitOne,
    '2': unicDigitTwo,
    '3': unicDigitThree,
    '4': unicDigitFour,
    '5': unicDigitFive,
    '6': unicDigitSix,
    '7': unicDigitSeven,
    '8': unicDigitEight,
    '9': unicDigitNine,
    '<': '\uD83D' + '\uDD43',
    '>': '\uD83D' + '\uDD44',
    '@': '\uA67E',
    'E': '\uE0E4',
    'F': unicCapitalFita,
    'I': unicCapitalUkrI,
    'J': '\u046A',
    'K': unicCapitalIotifLittleYus,
    'L': '\u046C',
    'O': unicCapitalRoundOmega,
    'P': '\u0470',
    'Q': unicCapitalOmegaTitled,
    'S': '\u0405',
    'T': unicCapitalOt,
    'U': unicCapitalUk,
    'V': unicCapitalIzhitsa,
    'W': unicCapitalOmega,
    'X': '\u046E',
    'Y': unicCapitalIzhitsaDblGrave,
    'Z': unicCapitalIotifA,
    'c': '\u1C83',
    'e': unicSmallUkrIe,
    'f': unicSmallFita,
    'g': unicSmallU,
    'i': unicSmallYi,
    'j': '\u046B',
    'k': unicSmallIotifLittleYus,
    'l': '\u046D',
    'm': '\uA641',
    'n': '\u0465',
    'o': unicSmallRoundOmega,
    'p': '\u0471',
    'q': unicSmallOmegaTitled,
    'r': unicSmallUkrI,
    's': '\u0455',
    't': unicSmallOt,
    'u': unicSmallUk,
    'v': unicSmallIzhitsa,
    'w': unicSmallOmega,
    'x': '\u046F',
    'y': unicSmallIzhitsaDblGrave,
    'z': unicSmallIotifA,
    '~': '\u0027',
    '°': '\u00AB',
    '±': '\u00AC',
    'Ē': '\u00B7',
    'У': unicCapitalMonogrUk,
    'Э': unicCapitalYat,
    'Я': unicCapitalLittleYus,
    'у': unicSmallMonogrUk,
    'э': unicSmallYat,
    'я': unicSmallLittleYus,
    '‡': Dagger,
}
# ========================================

